from math import sqrt
speedpersecond = (2)
A = (3)
B = (1)
a = (2)
b = (8)
Xdistance = (a-A)
Ydistance = (b-B)
Diagonaldistance = (Ydistance*Ydistance+Xdistance*Xdistance) 
Diagonaldistancenotsquared = sqrt(Diagonaldistance)
TimeToGetThere = (Diagonaldistancenotsquared/speedpersecond)
print (f" Going at a velocity of {speedpersecond} meters per second, it will take you {TimeToGetThere} seconds to get from A to B, traversing a distance of {Diagonaldistancenotsquared} meters")