from math import sqrt
time = (1)
speed = (24)
A = (3)
B = (1)
a = (2)
b = (8)
Xdistance = (a-A)
Ydistance = (b-B)
Diagonaldistance = (Ydistance*Ydistance+Xdistance*Xdistance) 
Diagonaldistancenotsquared = sqrt(Diagonaldistance)
TimeToGetThere = (Diagonaldistancenotsquared/speed)
print (f" Going at the velocity of {speed} meters per second,it will take you {TimeToGetThere} seconds to get from A to B, traversing a distance of {Diagonaldistancenotsquared} meters")